# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capcode-all-plugins}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregoire Lejeune"]
  s.date = %q{2010-02-03}
  s.description = %q{This gem install all Capcode plugins}
  s.email = %q{gregoire.lejeune@free.fr}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "capcode-all-plugins.gemspec"
  ]
  s.homepage = %q{http://github.com/glejeune/Capcode.more/tree/master/capcode-all-plugins}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This gem install all Capcode plugins}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capcode-base-activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-base-couch_foo>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-base-couchrest>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-base-datamapper>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-base-mongoid>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-base-sequel>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-binary>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-email>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-erb>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-haml>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-json>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-less>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-markaby>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-mustache>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-redirect>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-sass>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-static>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-webdav>, [">= 0"])
      s.add_runtime_dependency(%q<capcode-render-xml>, [">= 0"])
    else
      s.add_dependency(%q<capcode-base-activerecord>, [">= 0"])
      s.add_dependency(%q<capcode-base-couch_foo>, [">= 0"])
      s.add_dependency(%q<capcode-base-couchrest>, [">= 0"])
      s.add_dependency(%q<capcode-base-datamapper>, [">= 0"])
      s.add_dependency(%q<capcode-base-mongoid>, [">= 0"])
      s.add_dependency(%q<capcode-base-sequel>, [">= 0"])
      s.add_dependency(%q<capcode-render-binary>, [">= 0"])
      s.add_dependency(%q<capcode-render-coffee-script>, [">= 0"])
      s.add_dependency(%q<capcode-render-email>, [">= 0"])
      s.add_dependency(%q<capcode-render-erb>, [">= 0"])
      s.add_dependency(%q<capcode-render-haml>, [">= 0"])
      s.add_dependency(%q<capcode-render-json>, [">= 0"])
      s.add_dependency(%q<capcode-render-less>, [">= 0"])
      s.add_dependency(%q<capcode-render-markaby>, [">= 0"])
      s.add_dependency(%q<capcode-render-mustache>, [">= 0"])
      s.add_dependency(%q<capcode-render-redirect>, [">= 0"])
      s.add_dependency(%q<capcode-render-sass>, [">= 0"])
      s.add_dependency(%q<capcode-render-static>, [">= 0"])
      s.add_dependency(%q<capcode-render-webdav>, [">= 0"])
      s.add_dependency(%q<capcode-render-xml>, [">= 0"])
    end
  else
    s.add_dependency(%q<capcode-base-activerecord>, [">= 0"])
    s.add_dependency(%q<capcode-base-couch_foo>, [">= 0"])
    s.add_dependency(%q<capcode-base-couchrest>, [">= 0"])
    s.add_dependency(%q<capcode-base-datamapper>, [">= 0"])
    s.add_dependency(%q<capcode-base-mongoid>, [">= 0"])
    s.add_dependency(%q<capcode-base-sequel>, [">= 0"])
    s.add_dependency(%q<capcode-render-binary>, [">= 0"])
    s.add_dependency(%q<capcode-render-coffee-script>, [">= 0"])
    s.add_dependency(%q<capcode-render-email>, [">= 0"])
    s.add_dependency(%q<capcode-render-erb>, [">= 0"])
    s.add_dependency(%q<capcode-render-haml>, [">= 0"])
    s.add_dependency(%q<capcode-render-json>, [">= 0"])
    s.add_dependency(%q<capcode-render-less>, [">= 0"])
    s.add_dependency(%q<capcode-render-markaby>, [">= 0"])
    s.add_dependency(%q<capcode-render-mustache>, [">= 0"])
    s.add_dependency(%q<capcode-render-redirect>, [">= 0"])
    s.add_dependency(%q<capcode-render-sass>, [">= 0"])
    s.add_dependency(%q<capcode-render-static>, [">= 0"])
    s.add_dependency(%q<capcode-render-webdav>, [">= 0"])
    s.add_dependency(%q<capcode-render-xml>, [">= 0"])
  end
end

