require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "capcode-base-couch_foo"
    gem.summary = %Q{Capcode plugin to access CouchDB via couch_foo}
    gem.description = gem.summary
    gem.email = "gregoire.lejeune@free.fr"
    gem.homepage = "http://github.com/glejeune/Capcode.more/tree/master/%s" % gem.name
    gem.authors = ["Gregoire Lejeune"]

    gem.add_dependency('couch_foo')
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end
