# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capcode-render-webdav}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregoire Lejeune"]
  s.date = %q{2011-01-02}
  s.description = %q{Capcode plugin to create WebDav server}
  s.email = %q{gregoire.lejeune@free.fr}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capcode-render-webdav.gemspec",
    "examples/auth-webdav.rb",
    "examples/render-webdav.rb",
    "lib/capcode/render/webdav.rb"
  ]
  s.homepage = %q{http://github.com/glejeune/Capcode.more/tree/master/capcode-render-webdav}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Capcode plugin to create WebDav server}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack_dav>, [">= 0"])
    else
      s.add_dependency(%q<rack_dav>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack_dav>, [">= 0"])
  end
end

